import type { Metadata } from "next";
import { Suspense } from "react";
import { Geist_Mono, Lato, Raleway } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Providers from "@/app/providers";
import AnimatedBackground from "@/components/animated-background";

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${raleway.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <AnimatedBackground>
            <Suspense fallback={null}>
              <Navbar />
            </Suspense>
            <div className="pt-[140px]">{children}</div>
          </AnimatedBackground>
        </Providers>
      </body>
    </html>
  );
}
